# fly.toml app configuration file generated for facturacion-ganoherb on 2024-01-01T00:00:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "facturacion-ganoherb"
primary_region = "mia"  # Miami region, close to El Salvador

[build]

[env]
  PORT = "8000"
  PYTHONPATH = "/app"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false  # Mantener máquina corriendo para tier gratuito
  auto_start_machines = false  # Deshabilitar auto escalado
  min_machines_running = 1  # Exactamente 1 máquina corriendo
  processes = ["app"]

  [http_service.checks]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[[statics]]
  guest_path = "/app/staticfiles"
  url_prefix = "/static"

[deploy]
  release_command = "python manage.py migrate --noinput"

[processes]
  app = "gunicorn ganoherb_inventory_billing.wsgi:application --bind 0.0.0.0:8000 --workers 1 --max-requests 1000 --max-requests-jitter 100 --timeout 120" 