# fly.toml app configuration file generated for facturacion-ganoherb-withered-wind-2121 on 2025-06-04T10:37:26-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'facturacion-ganoherb-withered-wind-2121'
primary_region = 'mia'
console_command = '/app/manage.py shell'

[build]
  # Forzar a usar solo el Dockerfile, sin detección automática
  skip_remote_builder = false

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  PORT = '8000'
  PYTHONPATH = '/app'
  # Desactivar mise explícitamente
  MISE_DISABLE = '1'

[processes]
  app = 'gunicorn ganoherb_inventory_billing.wsgi:application --bind 0.0.0.0:8000 --workers 1 --max-requests 1000 --max-requests-jitter 100 --timeout 120'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[[statics]]
  guest_path = '/app/staticfiles'
  url_prefix = '/static/'
