# Generated by Django 5.1.2 on 2024-11-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='registration_number',
            field=models.CharField(blank=True, error_messages={'blank': 'El número de registro es requerido', 'null': 'El número de registro es requerido'}, max_length=12, null=True, verbose_name='Número de registro'),
        ),
    ]
