# Generated by Django 5.1.2 on 2024-11-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_customer_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[('FCC', 'Factura Consumidor Final'), ('CCF', 'Comprobante de Crédito Fiscal')], default='FCC', max_length=3, verbose_name='Tipo de Factura'),
        ),
    ]
