 # Generated by Django 5.1.2 on 2024-11-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_invoice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(error_messages={'blank': 'La dirección es requerida', 'null': 'La dirección es requerida'}, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, error_messages={'invalid': 'Ingrese un correo electrónico válido', 'unique': 'Ya existe un cliente con este correo electrónico'}, max_length=254, null=True, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nit',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(error_messages={'blank': 'El teléfono es requerido', 'null': 'El teléfono es requerido'}, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registration_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Número de registro'),
        ),
    ]
