# Generated by Django 5.1.2 on 2024-11-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterField(
            model_name='product',
            name='distributor_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio distribuidor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='public_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio público'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='product',
            name='units_per_box',
            field=models.IntegerField(verbose_name='Unidades por caja'),
        ),
    ]
