# Generated by Django 5.1.2 on 2024-11-06 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'El nombre del cliente es requerido', 'null': 'El nombre del cliente es requerido'}, max_length=200, verbose_name='Nombre')),
                ('code_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código de distribuidor')),
                ('email', models.EmailField(error_messages={'blank': 'El correo electrónico es requerido', 'invalid': 'Ingrese un correo electrónico válido', 'null': 'El correo electrónico es requerido', 'unique': 'Ya existe un cliente con este correo electrónico'}, max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('nit', models.CharField(error_messages={'blank': 'El NIT es requerido', 'null': 'El NIT es requerido'}, max_length=20, verbose_name='NIT')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.AlterModelOptions(
            name='invoicedetail',
            options={'verbose_name': 'Detalle de Factura', 'verbose_name_plural': 'Detalles de Factura'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(error_messages={'invalid': 'Ingrese una fecha válida', 'null': 'La fecha es requerida'}, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(error_messages={'blank': 'El número de factura es requerido', 'null': 'El número de factura es requerido', 'unique': 'Ya existe una factura con este número'}, max_length=20, unique=True, verbose_name='Número de factura'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Pagada'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='distributor_price',
            field=models.DecimalField(decimal_places=2, error_messages={'invalid': 'Ingrese un precio válido', 'null': 'El precio distribuidor es requerido'}, max_digits=10, verbose_name='Precio distribuidor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(error_messages={'blank': 'El nombre del producto es requerido', 'null': 'El nombre del producto es requerido'}, max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='public_price',
            field=models.DecimalField(decimal_places=2, error_messages={'invalid': 'Ingrese un precio válido', 'null': 'El precio público es requerido'}, max_digits=10, verbose_name='Precio público'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(error_messages={'invalid': 'Ingrese una cantidad válida', 'null': 'La cantidad es requerida'}, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='product',
            name='units_per_box',
            field=models.IntegerField(error_messages={'invalid': 'Ingrese un número válido', 'null': 'La cantidad de unidades por caja es requerida'}, verbose_name='Unidades por caja'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(error_messages={'null': 'Debe seleccionar un cliente'}, on_delete=django.db.models.deletion.CASCADE, to='inventory.customer', verbose_name='Cliente'),
        ),
        migrations.DeleteModel(
            name='Distributor',
        ),
    ]
